### ISSUE TITLE
Crawler will not create a new index

### ISSUE THREAD

**Issue by jeffvestal** [elastic/crawler#172]
## Bug Description
The crawler will not index unless I run 
`PUT search-labs-blogs` (index-name) first

### To Reproduce
Create an index template 
```
PUT _index_template/search-labs-template
{
  "index_patterns": [
    "search-labs-blogs*"
  ],
  "template": {
    "mappings": {
      "properties": {
        "body": {
          "type": "text",
          "copy_to": "body_semantic"
        },
        "body_semantic": {
          "type": "semantic_text",
          "inference_id": "elser-endpoint"
        },
        "last_crawled_at": {
          "type": "date"
        }
      }
    }
  }
}
```

## Expected behavior
index should be created

error log
```
# docker exec -it crawler bin/crawler crawl config/crawler.yml
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[crawl:674fdd29ea2d0bc3919dabc8] [primary] ES connections will be authorized with configured username and password
[crawl:674fdd29ea2d0bc3919dabc8] [primary] ES connections will use SSL without ca_fingerprint
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Elasticsearch sink initialized for index [elastic-labs] with pipeline [ent-search-generic-ingestion]
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Starting the primary crawl with up to 10 parallel thread(s)...
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=10, pages_visited=1, urls_allowed=11, urls_denied={:rule_engine_denied=>1}, crawl_duration_msec=1812, crawling_time_msec=619.0, avg_response_time_msec=619.0, active_threads=1, http_client={:max_connections=>100, :used_connections=>1}, status_codes={"200"=>1}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=8, pages_visited=13, urls_allowed=20, urls_denied={:rule_engine_denied=>1}, crawl_duration_msec=12053, crawling_time_msec=2127.0, avg_response_time_msec=163.6153846153846, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>13}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=8, pages_visited=13, urls_allowed=20, urls_denied={:rule_engine_denied=>109}, crawl_duration_msec=22080, crawling_time_msec=2127.0, avg_response_time_msec=163.6153846153846, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>13}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=8, pages_visited=13, urls_allowed=20, urls_denied={:rule_engine_denied=>1662}, crawl_duration_msec=32119, crawling_time_msec=2127.0, avg_response_time_msec=163.6153846153846, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>13}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=7, pages_visited=14, urls_allowed=20, urls_denied={:rule_engine_denied=>3910}, crawl_duration_msec=42145, crawling_time_msec=2560.0, avg_response_time_msec=182.85714285714286, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>14}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=6, pages_visited=15, urls_allowed=20, urls_denied={:rule_engine_denied=>6463}, crawl_duration_msec=52348, crawling_time_msec=3013.0, avg_response_time_msec=200.86666666666667, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>15}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=4, pages_visited=17, urls_allowed=20, urls_denied={:rule_engine_denied=>9203}, crawl_duration_msec=62386, crawling_time_msec=3969.0, avg_response_time_msec=233.47058823529412, active_threads=10, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>17}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=4, pages_visited=17, urls_allowed=20, urls_denied={:rule_engine_denied=>12754}, crawl_duration_msec=72394, crawling_time_msec=3969.0, avg_response_time_msec=233.47058823529412, active_threads=9, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>17}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>16358}, crawl_duration_msec=82395, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=3, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>19037}, crawl_duration_msec=92395, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=2, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>22095}, crawl_duration_msec=102411, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=2, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>25913}, crawl_duration_msec=112418, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=2, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>28500, :robots_txt_disallowed=>3285}, crawl_duration_msec=122430, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=2, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl status: queue_size=0, pages_visited=21, urls_allowed=20, urls_denied={:rule_engine_denied=>31766, :robots_txt_disallowed=>5977}, crawl_duration_msec=132432, crawling_time_msec=5895.0, avg_response_time_msec=280.7142857142857, active_threads=1, http_client={:max_connections=>100, :used_connections=>10}, status_codes={"200"=>21}
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl queue is empty, finishing the primary crawl
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Finished a crawl stage. Result: success; Successfully finished the primary crawl with an empty crawl queue
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Crawl Error: Unexpected error while running the crawl: Elastic::Transport::Transport::Errors::NotFound: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [elastic-labs]","resource.type":"index_or_alias","resource.id":"elastic-labs","index_uuid":"_na_","index":"elastic-labs"}],"type":"index_not_found_exception","reason":"no such index [elastic-labs]","resource.type":"index_or_alias","resource.id":"elastic-labs","index_uuid":"_na_","index":"elastic-labs"},"status":404} /usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/base.rb:228:in `__raise_transport_error'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/base.rb:346:in `perform_request'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/http/faraday.rb:36:in `perform_request'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/client.rb:197:in `perform_request'
/usr/local/bundle/gems/elasticsearch-8.13.0/lib/elasticsearch.rb:86:in `verify_elasticsearch'
/usr/local/bundle/gems/elasticsearch-8.13.0/lib/elasticsearch.rb:69:in `method_missing'
/usr/local/bundle/gems/elasticsearch-api-8.13.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-8.13.0/lib/elasticsearch/api/actions/indices/refresh.rb:58:in `refresh'
/app/lib/crawler/output_sink/elasticsearch.rb:83:in `fetch_purge_docs'
/app/lib/crawler/coordinator.rb:98:in `run_purge_crawl!'
/app/lib/crawler/coordinator.rb:72:in `run_crawl!'
/app/lib/crawler/api/crawl.rb:92:in `start!'
/app/lib/crawler/cli/crawl.rb:25:in `call'
/usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
/usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
bin/crawler:28:in `<main>'
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Finished a crawl. Result: failure; Unexpected error while running the crawl, check system logs for details
[crawl:674fdd29ea2d0bc3919dabc8] [primary] Releasing resources used by the crawl...

```

**Comment by seanstory** [comment]
My current theory is that this was introduced when we added a purge phase, and we just need to 
```
catch 404_error:
  return []
```
in `fetch_purge_docs()`

**Comment by navarone-feekery** [comment]
Ah found it: https://github.com/elastic/crawler/issues/53

**Comment by daveyholler** [comment]
@seanstory - What's up ol' pal?! I'm pulling up this old issue cause I just finished setting up start_local and running the open web crawler and came across the same thing. Google led me here.

```
[2025-09-02T00:19:12.584Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Search failed after 4 attempts: '[400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400}'
```

### Steps to reproduce:
1. configure `start_local`
2. Fire that bad boy up
3. Run the open crawler test
4. Setup the environment variables, `http://host.docker.internal`, `9200`, `https://traderjoes.com`
5. Hit the go button
6. The crawler connects, but fails to create the index

> Full logs:
```
crawler  export ES_HOST='http://host.docker.internal'
crawler  cat > crawl-config.yml << EOF
output_sink: elasticsearch
output_index: web-crawl-test

elasticsearch:
  host: $ES_HOST
  port: $ES_PORT
  api_key: $ES_API_KEY
  pipeline_enabled: false

domains:
  - url: $TARGET_WEBSITE
EOF
crawler  docker run \
  -v "$(pwd)":/config \
  -it docker.elastic.co/integrations/crawler:latest jruby \
  bin/crawler crawl /config/crawl-config.yml
OpenJDK 64-Bit Server VM warning: Unable to get SVE vector length on this system. Disabling SVE. Specify -XX:UseSVE=0 to shun this warning.
[2025-09-02T00:18:57.569Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Initialized an in-memory URL queue for up to 10000 URLs
[2025-09-02T00:18:57.573Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] ES connections will be authorized with configured API key
[2025-09-02T00:18:57.622Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Connected to ES at http://host.docker.internal:9200 - version: 9.1.3; build flavor: default
[2025-09-02T00:18:57.707Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Index [web-crawl-test] did not exist, but was successfully created!
[2025-09-02T00:18:57.707Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Elasticsearch sink initialized for index [web-crawl-test] with pipeline disabled
[2025-09-02T00:18:57.742Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Starting the primary crawl with up to 10 parallel thread(s)...
[2025-09-02T00:18:58.245Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Error while fetching robots.txt for https://www.traderjoes.com:443: Forbidden
[2025-09-02T00:18:58.272Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Crawl status: queue_size=0, pages_visited=1, urls_allowed=1, urls_denied={}, crawl_duration_msec=532, crawling_time_msec=422.0, avg_response_time_msec=422.0, active_threads=1, http_client={:max_connections=>100, :used_connections=>1}, status_codes={"403"=>1}
[2025-09-02T00:18:58.488Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Crawl queue is empty, finishing the primary crawl
[2025-09-02T00:18:58.489Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Finished a crawl stage. Result: success; Successfully finished the primary crawl with an empty crawl queue
[2025-09-02T00:18:58.535Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Search attempt 1/4 failed: '[400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400}'. Retrying in 2.0s..
[2025-09-02T00:19:00.552Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Search attempt 2/4 failed: '[400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400}'. Retrying in 4.0s..
[2025-09-02T00:19:04.568Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Search attempt 3/4 failed: '[400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400}'. Retrying in 8.0s..
[2025-09-02T00:19:12.584Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Search failed after 4 attempts: '[400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400}'.
[2025-09-02T00:19:12.584Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Crawl Error: Unexpected error while running the crawl: Elastic::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"web-crawl-test","node":"jkvvyHiYRiilnq4zLgd6Fw","reason":{"type":"query_shard_exception","reason":"No mapping found for [last_crawled_at] in order to sort on","index_uuid":"9ZhHCRwOQyS9haGMgg1z6Q","index":"web-crawl-test"}}]},"status":400} /usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/base.rb:228:in `__raise_transport_error'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/base.rb:346:in `perform_request'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/transport/http/faraday.rb:36:in `perform_request'
/usr/local/bundle/gems/elastic-transport-8.3.2/lib/elastic/transport/client.rb:197:in `perform_request'
/usr/local/bundle/gems/elasticsearch-8.13.0/lib/elasticsearch.rb:71:in `method_missing'
/usr/local/bundle/gems/elasticsearch-api-8.13.0/lib/elasticsearch/api/actions/search.rb:105:in `search'
/home/app/lib/es/client.rb:79:in `block in paginated_search'
/home/app/lib/es/client.rb:237:in `execute_with_retry'
/home/app/lib/es/client.rb:78:in `block in paginated_search'
org/jruby/RubyKernel.java:1725:in `loop'
/home/app/lib/es/client.rb:77:in `paginated_search'
/home/app/lib/crawler/output_sink/elasticsearch.rb:123:in `fetch_purge_docs'
/home/app/lib/crawler/coordinator.rb:98:in `run_purge_crawl!'
/home/app/lib/crawler/coordinator.rb:70:in `run_crawl!'
/home/app/lib/crawler/api/crawl.rb:88:in `start!'
/home/app/lib/crawler/cli/crawl.rb:25:in `call'
/usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
/usr/local/bundle/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
bin/crawler:28:in `<main>'
[2025-09-02T00:19:12.585Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Finished a crawl. Result: failure; Unexpected error while running the crawl, check system logs for details
[2025-09-02T00:19:12.586Z] [crawl:68b637f1c11ecbf8ecd9daa4] [primary] Releasing resources used by the crawl...

---- Crawl Stats ----
- Pages visited: 2
- URLs allowed: 1
- URLs denied
  - Already seen:
  - Domain filter:
- Crawl duration (seconds): 14
- Crawling time (seconds): 0.629
- Average response time (seconds): 0.3145
```
